---
- name: Creating Windows AD Domain
  hosts: all
  tasks:
  - name: ad
    win_domain:
      dns_domain_name: "{{ ansible_fqdn }}"
      safe_mode_password: r3dh4t1!
  - name: Installing AD features
    win_feature:
      name: AD-Domain-Services
      include_sub_features: yes
      include_management_tools: yes
      state: present
  - name: domain
    win_domain:
      create_dns_delegation: yes
      database_path: C:\Windows\NTDS
      dns_domain_name: "{{ ansible_fqdn }}"
      domain_mode: Win2012R2
      domain_netbios_name: EXAMPLE
      forest_mode: Win2012R2
      safe_mode_password: r3dh4t1!
      sysvol_path: C:\Windows\SYSVOL
    register: domain_install
  - name: Reboot Server
    win_reboot:
      msg: "Rebooting Server..."
      pre_reboot_delay: 60
    when: domain_install.reboot_required
