---
- name: Creating users
  hosts: all
  tasks:
  - name: Creating group
    win_domain_group:
      name: developers
      description: Developers Group
      state: present
      scope: global
  - name: Adding now
    win_domain_user:
      name: testing
      firstname: Rajat
      surname: Agrawal
      company: Red Hat Inc.
      password: r3dh4t1!
      state: present
      street: 123 E. Davie St.
      city: Raleigh
      state_province: NC
      postal_code: 12345
      country: US
      attributes:
        telephoneNumber: 111-123456
      password_expired: no
      groups:
          - Domain Admin
          - developers
      domain_user: EXAMPLE.COM\\Administrator
      domain_password: wRN*fAnEV%!cGWfDbMS.KKPol2B@enqS
      domain_server: EXAMPLE.COM
